name: ci

on: pull_request

jobs:
    test: 
        runs-on: ubuntu-latest

        steps:
          - name: Download the repository
            uses: action/checkout@v4
          
          - name: Install Python
            uses: action/setup/python@v5
            with:
              python-version: '3.11.5'

          - name: Install dependencies
            run: pip install -r requirements.txt

          - name: Run automated tests
            run: pytest tests/test_unit.py